spring:
  profiles:
    active: ${activatedProperties}
---
spring:
  config:
    activate:
      on-profile: rev
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: sa
    password: sa

logging:
  level:
    ru:
      akpsv: debug
    org:
      zalando:
        logbook: trace
      springframework:
        core:
          env: debug
server:
  port: 9090

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:file:./stat-svc-testdb/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

logging:
  level:
    ru:
      akpsv: debug
    org:
      zalando:
        logbook: TRACE
      springframework:
        core:
          env: DEBUG

server:
  port: 9090
