DROP TABLE IF EXISTS requests;

CREATE TABLE requests(
    request_id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requestor_app VARCHAR(255) NOT NULL ,
    request_uri VARCHAR(1024) NOT NULL ,
    requestor_ip VARCHAR(255) NOT NULL ,
    request_time TIMESTAMP NOT NULL
);