DROP TABLE IF EXISTS requests;

CREATE TABLE requests(
    request_id BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requestor_app VARCHAR,
    request_uri VARCHAR,
    requestor_ip VARCHAR,
    request_time TIMESTAMP
);