spring:
  profiles:
    active: '@activatedProperties@'

---
spring:
  config:
    activate:
      on-profile: rev
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://ewm-db:5432/ewmdb
    driver-class-name: org.postgresql.Driver
    username: sa
    password: sa

logging:
  level:
    ru:
      akpsv: debug
    org:
      zalando:
        logbook: TRACE
      springframework:
        core:
          env: DEBUG

main-svc:
  url: ${STATS_SERVER_URL}

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/ewm_postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
#datasource:
#    url: jdbc:h2:file:./testdb/test-main-svc
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: sa

logging:
  level:
    ru:
      akpsv: debug
    org:
      zalando:
        logbook: TRACE
      springframework:
        core:
          env: DEBUG

main-svc:
  url: "http://localhost:9090"

