spring:
  profiles:
    active: '@activatedProperties@'

---
spring:
  config:
    activate:
      on-profile: rev
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://ewm-db:5432/ewmdb
    driver-class-name: org.postgresql.Driver
    username: sa
    password: sa
  mail:
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    properties:
      mail:
        host: smtp.yandex.ru
        port: 465
        username: testewm@yandex.ru
        password: jfsfxoktowkmuydr
        properties:
          mail:
            protocol: smtps
            smtp:
              connectiontimeout: 5000
              timeout: 3000
              writetimeout: 5000
              auth: true
              ssl:
                enable: true

logging:
  level:
    ru:
      akpsv: debug
    org:
      zalando:
        logbook: TRACE
      springframework:
        core:
          env: DEBUG

main-svc:
  url: ${STATS_SERVER_URL}

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/ewm_postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  mail:
    host: smtp.yandex.ru
    port: 465
    username: testewm@yandex.ru
    password: jfsfxoktowkmuydr
    properties:
      mail:
        protocol: smtps
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          auth: true
          ssl:
            enable: true

mail:
  debug: true
#datasource:
#    url: jdbc:h2:file:./testdb/test-main-svc
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: sa

logging:
  level:
    ru:
      akpsv: debug
    org:
      zalando:
        logbook: TRACE
      springframework:
        core:
          env: DEBUG

main-svc:
  url: "http://localhost:9090"
